"""More detailed run infomation

Revision ID: 95e549073af8
Revises: 3354ecfab25a
Create Date: 2016-09-20 17:03:47.525521

"""

# revision identifiers, used by Alembic.
revision = '95e549073af8'
down_revision = '3354ecfab25a'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.types as ty


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Give it a default value first for DB to create corresponding column for existing rows
    op.add_column('run', sa.Column('ci_url', sa.String(length=1024), nullable=False, server_default='#'))
    op.add_column('run', sa.Column('product', sa.String(length=255), nullable=False, server_default='Unknown'))
    # Then remove the default value, make it not nullable.
    op.alter_column('run','description', type_=ty.Text())
    op.alter_column('run','ci_url', server_default=None)
    op.alter_column('run','product', server_default=None)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'product')
    op.drop_column('run', 'ci_url')
    op.alter_column('run','description', type_=ty.String(255))
    ### end Alembic commands ###
