"""First migration.

Revision ID: a7b58bb2b1dc
Revises: None
Create Date: 2016-08-24 15:24:39.372968

"""

# revision identifiers, used by Alembic.
revision = 'a7b58bb2b1dc'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
    pass
