"""empty message

Revision ID: d970ebbc5efa
Revises: 95e549073af8
Create Date: 2016-09-23 17:21:50.946581

"""

# revision identifiers, used by Alembic.
revision = 'd970ebbc5efa'
down_revision = '95e549073af8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'_test_run_id_uc', 'run', type_='unique')
    op.create_unique_constraint('_test_run_id_uc', 'run', ['name', 'date'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_test_run_id_uc', 'run', type_='unique')
    op.create_unique_constraint(u'_test_run_id_uc', 'run', ['name', 'type', 'build', 'version', 'arch', 'date'])
    ### end Alembic commands ###
