"""empty message

Revision ID: e37374d80f25
Revises: 6374505f9e6e
Create Date: 2017-02-04 15:26:04.727176

"""

# revision identifiers, used by Alembic.
revision = 'e37374d80f25'
down_revision = '6374505f9e6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('auto_error', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('auto_failed', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('auto_ignored', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('auto_missing', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('auto_nolinkage', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('auto_passed', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('auto_skipped', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('manual_error', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('manual_failed', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('manual_ignored', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('manual_passed', sa.Integer(), nullable=True))
    op.add_column('run', sa.Column('manual_skipped', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'manual_skipped')
    op.drop_column('run', 'manual_passed')
    op.drop_column('run', 'manual_ignored')
    op.drop_column('run', 'manual_failed')
    op.drop_column('run', 'manual_error')
    op.drop_column('run', 'auto_skipped')
    op.drop_column('run', 'auto_passed')
    op.drop_column('run', 'auto_nolinkage')
    op.drop_column('run', 'auto_missing')
    op.drop_column('run', 'auto_ignored')
    op.drop_column('run', 'auto_failed')
    op.drop_column('run', 'auto_error')
    ### end Alembic commands ###
