#!/usr/bin/env bash

#export DJANGO_SETTINGS_MODULE=libvirt_dashboard.settings

# Reset environment
rm -rf caselink/migrations db.sqlite3

# Reset database
python2 ./manage.py makemigrations caselink
python2 ./manage.py migrate

# Start initial database
python2 ./setup_db.py

# Run server
python2 ./manage.py runserver 0.0.0.0:8888
