"""empty message

Revision ID: 0d185f3785ee
Revises: bc72d02c107a
Create Date: 2017-05-04 19:06:28.164495

"""

# revision identifiers, used by Alembic.
revision = '0d185f3785ee'
down_revision = 'bc72d02c107a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('submit_task', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'submit_task')
    # ### end Alembic commands ###
