"""empty message

Revision ID: 10756fd531a5
Revises: f061a05c028d
Create Date: 2017-05-05 19:35:38.560510

"""

# revision identifiers, used by Alembic.
revision = '10756fd531a5'
down_revision = 'f061a05c028d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'auto_nolinkage')
    op.drop_column('run', 'auto_error')
    op.drop_column('run', 'auto_missing')
    op.drop_column('run', 'manual_skipped')
    op.drop_column('run', 'auto_ignored')
    op.drop_column('run', 'manual_ignored')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('manual_ignored', sa.INTEGER(), nullable=True))
    op.add_column('run', sa.Column('auto_ignored', sa.INTEGER(), nullable=True))
    op.add_column('run', sa.Column('manual_skipped', sa.INTEGER(), nullable=True))
    op.add_column('run', sa.Column('auto_missing', sa.INTEGER(), nullable=True))
    op.add_column('run', sa.Column('auto_error', sa.INTEGER(), nullable=True))
    op.add_column('run', sa.Column('auto_nolinkage', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
