"""Add polarion_id to Run model

Revision ID: 3354ecfab25a
Revises: a7b58bb2b1dc
Create Date: 2016-09-19 17:08:31.319139

"""

# revision identifiers, used by Alembic.
revision = '3354ecfab25a'
down_revision = 'a7b58bb2b1dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('polarion_id', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'polarion_id')
    ### end Alembic commands ###
