"""empty message

Revision ID: 49e9a584c762
Revises: e37374d80f25
Create Date: 2017-02-22 14:47:09.469081

"""

# revision identifiers, used by Alembic.
revision = '49e9a584c762'
down_revision = 'e37374d80f25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkage_results', sa.Column('detail', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkage_results', 'detail')
    ### end Alembic commands ###
