"""empty message

Revision ID: 6374505f9e6e
Revises: 9dc91bb7d2ba
Create Date: 2016-11-14 10:55:08.418923

"""

# revision identifiers, used by Alembic.
revision = '6374505f9e6e'
down_revision = '9dc91bb7d2ba'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.types as ty


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run', 'polarion_id', type_=ty.String(65535))
    op.alter_column('auto_result', 'skip', type_=ty.Text())
    op.alter_column('auto_result', 'failure', type_=ty.Text())
    op.alter_column('auto_result', 'comment', type_=ty.Text())
    op.alter_column('manual_result', 'comment', type_=ty.Text())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run', 'polarion_id', type_=ty.String(1024))
    op.alter_column('auto_result', 'skip', type_=ty.String(65535))
    op.alter_column('auto_result', 'failure', type_=ty.String(65535))
    op.alter_column('auto_result', 'comment', type_=ty.String(65535))
    op.alter_column('manual_result', 'comment', type_=ty.String(65535))
    ### end Alembic commands ###

