"""empty message

Revision ID: 79d03eea0366
Revises: c69dde0194f8
Create Date: 2016-10-12 14:27:30.237409

"""

# revision identifiers, used by Alembic.
revision = '79d03eea0366'
down_revision = 'c69dde0194f8'

from alembic import op
import sqlalchemy as sa
import sqlalchemy.types as ty


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('property', 'value', type_=ty.String(65535))
    op.alter_column('run', 'ci_url', type_=ty.String(65535))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run', 'ci_url', type_=ty.String(1024))
    op.alter_column('property', 'value', type_=ty.String(1024))
    ### end Alembic commands ###
