"""empty message

Revision ID: 9dc91bb7d2ba
Revises: f6d833096f97
Create Date: 2016-11-10 13:13:32.798631

"""

# revision identifiers, used by Alembic.
revision = '9dc91bb7d2ba'
down_revision = 'f6d833096f97'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_result', sa.Column('result', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_result', 'result')
    ### end Alembic commands ###
