"""empty message

Revision ID: bc72d02c107a
Revises: d4e5f63a3dad
Create Date: 2017-05-04 18:34:19.649574

"""

# revision identifiers, used by Alembic.
revision = 'bc72d02c107a'
down_revision = 'd4e5f63a3dad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auto_result_case'), 'auto_result', ['case'], unique=False)
    op.create_index(op.f('ix_auto_result_result'), 'auto_result', ['result'], unique=False)
    op.create_index(op.f('ix_auto_result_run_id'), 'auto_result', ['run_id'], unique=False)
    op.create_index(op.f('ix_manual_result_run_id'), 'manual_result', ['run_id'], unique=False)
    op.create_index(op.f('ix_property_name'), 'property', ['name'], unique=False)
    op.create_index(op.f('ix_run_name'), 'run', ['name'], unique=False)
    op.create_index(op.f('ix_run_submit_date'), 'run', ['submit_date'], unique=False)
    op.create_index(op.f('ix_run_submit_status'), 'run', ['submit_status'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('ix_test_run_tags_run_id'), 'test_run_tags', ['run_id'], unique=False)
    op.create_index(op.f('ix_test_run_tags_tag_name'), 'test_run_tags', ['tag_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_run_tags_tag_name'), table_name='test_run_tags')
    op.drop_index(op.f('ix_test_run_tags_run_id'), table_name='test_run_tags')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_run_submit_status'), table_name='run')
    op.drop_index(op.f('ix_run_submit_date'), table_name='run')
    op.drop_index(op.f('ix_run_name'), table_name='run')
    op.drop_index(op.f('ix_property_name'), table_name='property')
    op.drop_index(op.f('ix_manual_result_run_id'), table_name='manual_result')
    op.drop_index(op.f('ix_auto_result_run_id'), table_name='auto_result')
    op.drop_index(op.f('ix_auto_result_result'), table_name='auto_result')
    op.drop_index(op.f('ix_auto_result_case'), table_name='auto_result')
    # ### end Alembic commands ###
