"""Add submit_status column

Revision ID: d4e5f63a3dad
Revises: 49e9a584c762
Create Date: 2017-05-02 15:48:08.199712

"""

# revision identifiers, used by Alembic.
revision = 'd4e5f63a3dad'
down_revision = '49e9a584c762'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('submit_status', sa.String(length=4095), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'submit_status')
    # ### end Alembic commands ###
