"""empty message

Revision ID: f061a05c028d
Revises: 0d185f3785ee
Create Date: 2017-05-05 14:27:33.370187

"""

# revision identifiers, used by Alembic.
revision = 'f061a05c028d'
down_revision = '0d185f3785ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('submit_log', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'submit_log')
    # ### end Alembic commands ###
